cmake_minimum_required(VERSION 3.28)
project(QuantFinance LANGUAGES CXX)
add_executable(quant)
target_sources(quant PRIVATE main.cpp)
target_compile_features(quant PRIVATE cxx_std_17)
add_executable(test)
target_sources(test PRIVATE tests/main.cpp tests/domain/test_consistency.cpp src/domain/VanillaOption.cpp src/domain/Option.cpp src/domain/formulas.cpp src/core/distributions.cpp)
target_compile_features(test PRIVATE cxx_std_17)
message(STATUS "PROJECT_NAME: " ${PROJECT_NAME})
